version: '3'

services:
    mysql:
        image: mysql
        container_name: api-nest-typeorm
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql

        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
